### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by AI-Pranto**
#229

Cleanup after installing
- NJOY2016
- embree

### CODE REVIEW

**Comment by AI-Pranto** [comment]
@Shimwell I am waiting for your review. I didn't include `double-down` for restoring space because it's a small file. But if you want, I can include it too.

**Comment by Shimwell** [comment]
Thanks for this PR we shall merge in rebuild and look forward to the reduced size. Much appreciated. I think we are gathering a nice set of improvements for the openmc docker file as well

**Comment by Shimwell** [comment]
Thanks for spotting the 2nd cmake, not sure why we had that in there. I think we found the version of the pip install cmake was newer

**Comment by Shimwell** [comment]
@billingsley-john spotted a MOAB mistake I made, so we can fix this once merged

**Pull request merged**
