### PR TITLE
Update old and new install-scripts

### PR DESCRIPTION
**Pull request by AI-Pranto**
- Include Intel’s Embree ray tracer via the double down project in the new `DAGMC` release.

### CODE REVIEW

**Comment by Shimwell** [comment]
Thanks for this PR much appreciated. 

We have neglected the install scripts folder for a while so the tidy up is great timing. 

We are just focused on the Docker install at the moment but will get this reviewed and merged in soon.

Thanks

**Comment by AI-Pranto** [comment]
@Shimwell I have updated Docker script too.

**Comment by Shimwell** [comment]
Thanks, I might have also tidied up the Docker script (#219 ) but I will take a look and see if I've missed anything, thanks.

**Comment by Shimwell** [comment]
The Dockerfile has some nice improvements. The Dockerfile on this branch is unfortunately a bit out of date with the Develop Dockerfile (which we have been working on).

I think this whole branch is a bit out of date with the main Develop and Main branches but we can try to get you changes into the main branches

In general the install scripts folder was a bit of a dumping ground to store things. But really we should sort it out and this PR is a great start.

@billingsley-john is more familiar with these scripts so I shall let him comment but I guess we can delete some old scripts and aim to have one with conda and CQ and one without

**Comment by Shimwell** [comment]
lets merge this then see what can be brought into the develop branch

**Pull request merged**
